export function generateHooks(verifyCommand: string): string {
  const escaped = verifyCommand.replace(/'/g, "'\\''");
  return `#!/usr/bin/env bash
set -uo pipefail

# Verification gate — runs after each agent iteration
# Generated by @loop-eng/kit

echo 'Running verification: ${escaped}'
set +e
${verifyCommand}
exit_code=\$?
set -e

if [ \$exit_code -eq 0 ]; then
  echo "✓ Verification passed"
else
  echo "✗ Verification failed (exit code: \$exit_code)"
  exit \$exit_code
fi
`;
}
