import { LTF_TRACE_PATH, LTF_TRACER_STATE_PATH, LTF_VERSION } from "../utils/ltf-paths.js";

const TRACE_BASENAME = LTF_TRACE_PATH.split("/").pop();
const STATE_BASENAME = LTF_TRACER_STATE_PATH.split("/").pop();

export function generateHooks(verifyCommand: string): string {
  const shellEchoEscaped = verifyCommand.replace(/'/g, "'\\''");
  // JSON.stringify() produces a JSON-string literal (surrounding quotes
  // included). Escaping ITS single quotes lets us embed that literal
  // safely inside a single-quoted bash assignment; the value is later
  // substituted via printf's %s as an argument (never spliced into a
  // format string), so embedded '%' or backtick characters in the verify
  // command can't be reinterpreted by printf or the shell.
  const jsonEscaped = JSON.stringify(verifyCommand).replace(/'/g, "'\\''");

  return `#!/usr/bin/env bash
set -uo pipefail

# Verification gate — runs after each agent iteration
# Generated by @loop-eng/kit

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 && pwd)"
case "$SCRIPT_DIR" in
  */.claude/hooks)
    TRACE_ROOT="$(cd "$SCRIPT_DIR/../../.loop" >/dev/null 2>&1 && pwd)"
    [ -n "$TRACE_ROOT" ] || TRACE_ROOT="$SCRIPT_DIR"
    ;;
  *)
    TRACE_ROOT="$SCRIPT_DIR"
    ;;
esac
mkdir -p "$TRACE_ROOT" 2>/dev/null || true
TRACE_FILE="$TRACE_ROOT/${TRACE_BASENAME}"
STATE_FILE="$TRACE_ROOT/${STATE_BASENAME}"
VERIFY_CMD_JSON='${jsonEscaped}'

now_ms() {
  local raw
  raw=$(date +%s%3N 2>/dev/null || true)
  if [[ "$raw" =~ ^[0-9]+$ ]]; then
    printf '%s' "$raw"
  else
    printf '%s' "$(( $(date +%s) * 1000 ))"
  fi
}

echo 'Running verification: ${shellEchoEscaped}'

start_ms=$(now_ms)
set +e
( ${verifyCommand} )
exit_code=$?
set -e
end_ms=$(now_ms)
duration_ms=$(( end_ms - start_ms ))

if [ "$exit_code" -eq 0 ]; then
  echo "✓ Verification passed"
  result_status="success"
else
  echo "✗ Verification failed (exit code: $exit_code)"
  result_status="fail"
fi

# --- LTF trace emission (best-effort; never blocks verification) ---
{
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  if [ ! -f "$STATE_FILE" ]; then
    new_loop_id=$(command -v uuidgen >/dev/null 2>&1 && uuidgen | tr '[:upper:]' '[:lower:]' || printf 'loop-%s-%s' "$(date +%s)" "$$")
    printf '{"loop_id":"%s","started_at":"%s","iteration":0,"total_duration_ms":0,"summarized":0}' "$new_loop_id" "$timestamp" > "$STATE_FILE" 2>/dev/null || true
  fi

  state_content=$(cat "$STATE_FILE" 2>/dev/null || echo '{}')
  loop_id=$(printf '%s' "$state_content" | grep -o '"loop_id":"[^"]*"' | head -1 | cut -d'"' -f4)
  started_at=$(printf '%s' "$state_content" | grep -o '"started_at":"[^"]*"' | head -1 | cut -d'"' -f4)
  iteration=$(printf '%s' "$state_content" | grep -o '"iteration":[0-9]*' | head -1 | grep -o '[0-9]*$')
  total_duration_ms=$(printf '%s' "$state_content" | grep -o '"total_duration_ms":[0-9]*' | head -1 | grep -o '[0-9]*$')
  summarized=$(printf '%s' "$state_content" | grep -o '"summarized":[0-9]*' | head -1 | grep -o '[0-9]*$')
  [ -n "$loop_id" ] || loop_id="unknown"
  [ -n "$started_at" ] || started_at="$timestamp"
  [ -n "$iteration" ] || iteration=0
  [ -n "$total_duration_ms" ] || total_duration_ms=0
  [ -n "$summarized" ] || summarized=0
  iteration=$(( iteration + 1 ))
  total_duration_ms=$(( total_duration_ms + duration_ms ))

  # loop_summary is a one-time record per loop_id (SPEC.md: emitted once at
  # loop end) — track whether it's already been written so re-running
  # verify.sh after the loop already succeeded doesn't append a duplicate.
  already_summarized=$summarized
  if [ "$result_status" = "success" ] && [ "$summarized" -eq 0 ]; then
    summarized=1
  fi

  printf '{"loop_id":"%s","started_at":"%s","iteration":%d,"total_duration_ms":%d,"summarized":%d}' \\
    "$loop_id" "$started_at" "$iteration" "$total_duration_ms" "$summarized" > "$STATE_FILE" 2>/dev/null || true

  printf '{"ltf_version":"${LTF_VERSION}","loop_id":"%s","timestamp":"%s","phase":"verify","iteration":%d,"action":{"type":"test_run","target":%s},"verification":{"command":%s,"exit_code":%d},"duration_ms":%d,"result":{"status":"%s"}}\\n' \\
    "$loop_id" "$timestamp" "$iteration" "$VERIFY_CMD_JSON" "$VERIFY_CMD_JSON" "$exit_code" "$duration_ms" "$result_status" >> "$TRACE_FILE"

  if [ "$result_status" = "success" ] && [ "$already_summarized" -eq 0 ]; then
    printf '{"ltf_version":"${LTF_VERSION}","loop_id":"%s","timestamp":"%s","phase":"terminate","result":{"status":"success","detail":"goal_met"}}\\n' \\
      "$loop_id" "$timestamp" >> "$TRACE_FILE"
    printf '{"ltf_version":"${LTF_VERSION}","type":"loop_summary","loop_id":"%s","started_at":"%s","ended_at":"%s","total_iterations":%d,"total_duration_ms":%d,"termination_reason":"goal_met"}\\n' \\
      "$loop_id" "$started_at" "$timestamp" "$iteration" "$total_duration_ms" >> "$TRACE_FILE"
  fi
} 2>/dev/null || true

exit "$exit_code"
`;
}
